;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Salvage",DevComment="")
GameplayTagList=(Tag="Salvage.Thermos",DevComment="")
GameplayTagList=(Tag="Weapons",DevComment="")
GameplayTagList=(Tag="Weapons.Heavy",DevComment="")
GameplayTagList=(Tag="Weapons.Pistol",DevComment="")
GameplayTagList=(Tag="Weapons.Rifle",DevComment="")
GameplayTagList=(Tag="Weapons.Unarmed",DevComment="")

