;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="CrewQuartersDoor1",DevComment="")
GameplayTagList=(Tag="CrewQuartersDoor2",DevComment="")
GameplayTagList=(Tag="Sector1",DevComment="")
GameplayTagList=(Tag="Sector2",DevComment="")
GameplayTagList=(Tag="Sector3",DevComment="")
GameplayTagList=(Tag="Sector4",DevComment="")
GameplayTagList=(Tag="Sector5",DevComment="")
GameplayTagList=(Tag="Sector6",DevComment="")
GameplayTagList=(Tag="Sector7",DevComment="")
GameplayTagList=(Tag="Sector1.Bridge",DevComment="")
GameplayTagList=(Tag="Sector1.Bridge.Lights",DevComment="")
GameplayTagList=(Tag="Sector1.Cargo1",DevComment="")
GameplayTagList=(Tag="Sector1.Cargo1.Lights",DevComment="")
GameplayTagList=(Tag="Sector1.HallLights",DevComment="")
GameplayTagList=(Tag="Sector2.BreakerRoom",DevComment="")
GameplayTagList=(Tag="Sector2.BreakerRoom.Lights",DevComment="")
GameplayTagList=(Tag="Sector2.CommonArea",DevComment="")
GameplayTagList=(Tag="Sector2.CommonArea.Lights",DevComment="")
GameplayTagList=(Tag="Sector2.Galley",DevComment="")
GameplayTagList=(Tag="Sector2.Galley.Lights",DevComment="")
GameplayTagList=(Tag="Sector2.HallLights",DevComment="")
GameplayTagList=(Tag="Sector3.HallLights",DevComment="")
GameplayTagList=(Tag="Sector3.Hydroponics",DevComment="")
GameplayTagList=(Tag="Sector3.Hydroponics.Lights",DevComment="")
GameplayTagList=(Tag="Sector3.R&D",DevComment="")
GameplayTagList=(Tag="Sector3.R&D.Lights",DevComment="")
GameplayTagList=(Tag="Sector3.Reactor",DevComment="")
GameplayTagList=(Tag="Sector3.Reactor.Lights",DevComment="")
GameplayTagList=(Tag="Sector3.WaterFiltration",DevComment="")
GameplayTagList=(Tag="Sector3.WaterFiltration.Lights",DevComment="")

