;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Sector1",DevComment="")
GameplayTagList=(Tag="Sector2",DevComment="")
GameplayTagList=(Tag="Sector3",DevComment="")
GameplayTagList=(Tag="Sector4",DevComment="")
GameplayTagList=(Tag="Sector5",DevComment="")
GameplayTagList=(Tag="Sector1.Hallways",DevComment="")
GameplayTagList=(Tag="Sector1.Lounge",DevComment="")
GameplayTagList=(Tag="Sector1.MessHall",DevComment="")
GameplayTagList=(Tag="Sector1.Office1",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.1",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.2",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.3",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.4",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.5",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.6",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.7",DevComment="")
GameplayTagList=(Tag="Sector1.Quarters.8",DevComment="")
GameplayTagList=(Tag="Sector1.Recreation",DevComment="")
GameplayTagList=(Tag="Sector2.Comms",DevComment="")
GameplayTagList=(Tag="Sector2.Hallways",DevComment="")
GameplayTagList=(Tag="Sector2.Lockers",DevComment="")
GameplayTagList=(Tag="Sector2.Office2",DevComment="")
GameplayTagList=(Tag="Sector2.Office3",DevComment="")
GameplayTagList=(Tag="Sector2.PrimaryControl",DevComment="")
GameplayTagList=(Tag="Sector2.Servers",DevComment="")
GameplayTagList=(Tag="Sector3.Cultures",DevComment="")
GameplayTagList=(Tag="Sector3.Engineering",DevComment="")
GameplayTagList=(Tag="Sector3.Hallways",DevComment="")
GameplayTagList=(Tag="Sector3.Laboratories",DevComment="")
GameplayTagList=(Tag="Sector3.MedBay",DevComment="")
GameplayTagList=(Tag="Sector3.Office4",DevComment="")
GameplayTagList=(Tag="Sector3.Office5",DevComment="")
GameplayTagList=(Tag="Sector3.Office6",DevComment="")
GameplayTagList=(Tag="Sector4.Hallways",DevComment="")
GameplayTagList=(Tag="Sector4.Hydroponics",DevComment="")
GameplayTagList=(Tag="Sector4.LifeSupport",DevComment="")
GameplayTagList=(Tag="Sector4.Office7",DevComment="")
GameplayTagList=(Tag="Sector4.PowerControl",DevComment="")
GameplayTagList=(Tag="Sector4.Reactor",DevComment="")
GameplayTagList=(Tag="Sector5.CargoBay",DevComment="")
GameplayTagList=(Tag="Sector5.ColdStorage",DevComment="")
GameplayTagList=(Tag="Sector5.DockingBay",DevComment="")
GameplayTagList=(Tag="Sector5.Hallways",DevComment="")
GameplayTagList=(Tag="Sector5.Office8",DevComment="")
GameplayTagList=(Tag="Sector5.Refinery",DevComment="")

