;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Sector1",DevComment="")
GameplayTagList=(Tag="Sector2",DevComment="")
GameplayTagList=(Tag="Sector3",DevComment="")
GameplayTagList=(Tag="Sector4",DevComment="")
GameplayTagList=(Tag="Sector5",DevComment="")
GameplayTagList=(Tag="Sector1.Hallways",DevComment="")
GameplayTagList=(Tag="Sector2.Hallways",DevComment="")
GameplayTagList=(Tag="Sector3.Hallways",DevComment="")
GameplayTagList=(Tag="Sector4.Hallways",DevComment="")
GameplayTagList=(Tag="Sector5.Hallways",DevComment="")

