;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Weapons.Heacy",NewTagName="Weapons.Heavy")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="InteractPrompts",DevComment="")
+GameplayTagList=(Tag="InteractPrompts.Insert",DevComment="")
+GameplayTagList=(Tag="InteractPrompts.Open",DevComment="")
+GameplayTagList=(Tag="InteractPrompts.PickUp",DevComment="")
+GameplayTagList=(Tag="InteractPrompts.TurnOn",DevComment="")
+GameplayTagList=(Tag="Unarmed",DevComment="")

